name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]
    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Checkout Yourproject
        uses: actions/checkout@v2
        with:
          path: yourproject
      - name: Verify Yourproject is nicely formatted
        run: |
          v fmt -verify yourproject/
      - name: Build Yourproject
        run: |
          v yourproject/
      - name: Run Yourproject tests
        run: |
          v test yourproject/
